version: "3"
services:
  api:
    restart: always
    build: .
    container_name: 'python3-minimum'
    ports:
      - "80:80"
    tty: true
    volumes:
      - "./src:/app/src"
      # :cachedで変更が即時反映されるようにしておく。
      - "./pyproject.toml:/app/pyproject.toml:cached"
