version: "3"
services:
  api:
    restart: always
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    container_name: "python-movie"
    tty: true
    volumes:
      - "./src:/app/src"
      # :cachedで変更が即時反映されるようにしておく。
      - "./pyproject.toml:/app/pyproject.toml:cached"
